services:
  phpbb:
    image: bitnami/phpbb:3.3.11
    ports:
      - '127.0.0.12:80:8080'
    volumes:
      - 'phpbb:/bitnami/phpbb'
      - './setup.sh:/docker-entrypoint-init.d/setup.sh'
      - './styles/jediholo:/phpbb/styles/jediholo'
    environment:
      - PHPBB_USERNAME=admin
      - PHPBB_PASSWORD=admin
      - PHPBB_FORUM_NAME=JEDI Comport
      - PHPBB_FORUM_DESCRIPTION=The JEDI HoloNet Communications Port
      - PHPBB_EMAIL=admin@jediholo.net
      - PHPBB_DATABASE_HOST=mysql
      - PHPBB_DATABASE_USER=jediholo
      - PHPBB_DATABASE_PASSWORD=jediholo
      - PHPBB_DATABASE_NAME=jedi-comport
  mysql:
    image: mariadb:10.11
    ports:
      - '127.0.0.12:3306:3306'
    volumes:
      - 'mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=jediholo
      - MYSQL_USER=jediholo
      - MYSQL_PASSWORD=jediholo
      - MYSQL_DATABASE=jedi-comport
volumes:
  mysql:
  phpbb:
