services:
  phpbb:
    image: ghcr.io/jediholo/jedi-comport:master
    restart: on-failure
    build:
      context: .
    ports:
      - '127.0.0.12:80:8080'
    volumes:
      - 'phpbb-files:/srv/www/apps/phpbb/files'
      - 'phpbb-images:/srv/www/apps/phpbb/images'
      - 'phpbb-store:/srv/www/apps/phpbb/store'
      - './styles/jediholo:/srv/www/apps/phpbb/styles/jediholo'
    environment:
      - PHPBB_USERNAME=admin
      - PHPBB_PASSWORD=admin123
      - PHPBB_FORUM_NAME=JEDI Comport
      - PHPBB_FORUM_DESCRIPTION=The JEDI HoloNet Communications Port
      - PHPBB_EMAIL=admin@jediholo.net
      - PHPBB_DATABASE_HOST=mysql
      - PHPBB_DATABASE_USER=jediholo
      - PHPBB_DATABASE_PASSWORD=jediholo
      - PHPBB_DATABASE_NAME=jedi-comport
  mysql:
    image: mariadb:10.11
    restart: on-failure
    ports:
      - '127.0.0.12:3306:3306'
    volumes:
      - 'mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=jediholo
      - MYSQL_USER=jediholo
      - MYSQL_PASSWORD=jediholo
      - MYSQL_DATABASE=jedi-comport
volumes:
  mysql:
  phpbb-files:
  phpbb-images:
  phpbb-store:
