version: '3.5'
services:
  phpbb:
    image: bitnami/phpbb:3.3.4
    ports:
      - '127.0.0.12:80:8080'
    volumes:
      - './.docker/phpbb:/bitnami/phpbb'
      - './setup.sh:/docker-entrypoint-init.d/setup.sh'
      - './styles/jediholo:/phpbb/styles/jediholo'
    environment:
      - PHPBB_USERNAME=admin
      - PHPBB_PASSWORD=admin
      - PHPBB_FIRST_NAME=System
      - PHPBB_LAST_NAME=Administrator
      - PHPBB_FORUM_NAME=JEDI Comport
      - PHPBB_FORUM_DESCRIPTION=The JEDI HoloNet Communications Port
      - PHPBB_EMAIL=admin@jediholo.net
      - PHPBB_DATABASE_HOST=mysql
      - PHPBB_DATABASE_USER=jediholo
      - PHPBB_DATABASE_PASSWORD=jediholo
      - PHPBB_DATABASE_NAME=jedi-comport
  mysql:
    image: ghcr.io/fab-infra/mariadb:10.4-opensuse15
    ports:
      - '127.0.0.12:3306:3306'
    volumes:
      - './.docker/mysql:/var/lib/mysql'
    environment:
      MYSQL_USER: jediholo
      MYSQL_PASSWORD: jediholo
      MYSQL_DATABASE: jedi-comport
