name: Docker Build

on:
  push:
  schedule:
  - cron: '15 3 * * 0'
  workflow_dispatch:

jobs:
  build:
    uses: fab-infra/actions/.github/workflows/docker-build.yml@master
    with:
      docker-image: jedi-comport
